POST_URL = "https://www.handelsregister.de/rp_web/erweitertesuche.xhtml"
GET_URL = "https://www.handelsregister.de/rp_web/ergebnisse.xhtml"
CITY_CODE = "apiData/cities_code.json"
POST_REQUEST_PAYLOAD = "apiData/payload.json"
GET_REQUEST_HEADER_PATH = "apiData/headers.json"